version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    container_name: elasticsearch
    environment:
      cluster.name: "cloudwatch_cluster"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es

  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.1
    ports:
      # Beats input -- https://www.elastic.co/guide/en/logstash/5.0/plugins-inputs-beats.html
      - 5044:5044

      # UDP input -- https://www.elastic.co/guide/en/logstash/master/plugins-inputs-udp.html#plugins-inputs-udp-codec
      - 43448:43448/udp

      # Monitoring APIs -- https://www.elastic.co/guide/en/logstash/5.0/monitoring.html
      - 9600:9600
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs:/usr/share/logstash/data
    depends_on:
      - elasticsearch
    networks:
      - es

  kibana:
    image: kibana:latest
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - es

volumes:
  esdata1:
    driver: local

networks:
  es:
    driver: bridge
